### ISSUE TITLE
prod/staging

### ISSUE THREAD

**Issue by lsmith77** [tao-software/tao-schedule-update#11]
we are using wordpress as a content authoring system for a separate shop system. that is content is created in wordpress and then exported via a custom php script (using `get_pages()` and `get_post_meta()`) that dumps out a json structure that is imported into the shop.

we have two shop systems: staging and production. we have a simple publish process where authors can choose to deploy the entire content to either the staging system or the production system. this means that in order to test out something on staging, content authors need to:
* briefly publish a page
* push to staging
* revert back to draft

(and of course hope that during this time nobody published to production)

Of course once a page as been published once, there isn't even any way to prevent the update from being picked up on the next production push.

So what I would like to offer is the ability to offer the following states:

* draft state (will not get exported to staging or prod)
* published (will get exported to staging but not prod)
* scheduled for prod (will get exported to staging and prod)

Now when updating a post any change will immediately be visible for staging but in order for the change to appear in prod it would always be required to be scheduled for publishing, even if its right now.

Is this something which could be implemented on top of this plugin?

**Comment by Syberspace** [comment]
I don't think tao-schedule-update is what you're looking for in your usecase.
You should simply add the desired post states with [`register_post_status`](https://developer.wordpress.org/reference/functions/register_post_status/) and adapt your custom php script to only export the desired states.

**Comment by lsmith77** [comment]
yeah that will work for new posts .. but not for updates to existing posts

**Comment by Syberspace** [comment]
then that's an issue with your custom script and definitely out of scope for tao-schedule-update
