### ISSUE TITLE
Plugin not visible in WP version 4.8

### ISSUE THREAD

**Issue by 5y54dm1n** [tao-software/tao-schedule-update#12]
As subject. Can't find any way to access settings or schedule changes. Version issue with Wordpress?

**Comment by 5y54dm1n** [comment]
Nvm. Found the schedule settings and date picker. Just to verify; There is no plugin link in the menu to options/settings?

**Comment by Syberspace** [comment]
The plugin itself does not appear in the sidebar menu, there are a couple of options available through Settings->Scheduled Update.
Everything else is handled on the edit screen for scheduled updates.
