### ISSUE TITLE
Request: Update an update

### ISSUE THREAD

**Issue by KSAMissionCtrl** [tao-software/tao-schedule-update#13]
I have a page that needs to be updated in the future, so I click to schedule an update - all well and good. But now what if I want to schedule an update for after the first one? Meaning I want to schedule a second update but base it upon all the changes I scheduled for the first update. Currently I just have to copy/paste the contents of the first update into the second and then edit from there. Would be nice if the scheduled updates themselves have an option to schedule an update off of them.

I hope that all made sense

**Comment by MDylan** [comment]
Yes, this will be very helpfull!

**Comment by Syberspace** [comment]
This is already available in the current version.
It's called **recursive scheduling** and can be activated through Settings->Scheduled Upate
