### ISSUE TITLE
tao_sc_publish_pubdate didn't save sometimes

### ISSUE THREAD

**Issue by alexpoon2000** [tao-software/tao-schedule-update#16]
I am using woocommerce, WPML and enfold theme with this schedule update plugin. I found it doesn't work sometimes. After the scheduled time, the schedule product (post) didn't update sometimes. 

I am sure my timezone setting is corrent and the scheduled time is all at least 10 minutes after now.

After some checking, I found the post didn't work because "tao_sc_publish_pubdate" value didn't added or saved to the wp_postmeta table sometimes. I can't tell "when" will this "sometimes" happen. 

anyone has the same problem? and how can this be fixed?

**Comment by mpeterson28** [comment]
I'm not sure when this started happening, but my scheduled updates never go live. It has been going on for at least a month. I deactivated all plugins except for my theme and woocommerce, and it still does not work.

**Comment by Syberspace** [comment]
Which versions of tao-schedule-update and WordPress are you using?
