### ISSUE TITLE
Can not set the publish time to less than the difference between UTC and My time

### ISSUE THREAD

**Issue by thomasmery** [tao-software/tao-schedule-update#17]
Hi there,

thanks for the plugin, works great

but trying to set the publish date to same date and a time that is less than UTC Time + my Time zone time offset results in an error message:

`The releasedate is in the past.This post will be published 5 minutes from now.`

This seems to be related to line 32 of `publish-datepicker.js` which appears to be setting the publish date to UTC time and then comparing it to user's Time Zone _now_ time set on line 25 with `new Date()`

commenting line 32 seems to result in the expected behaviour

maybe I'm mistaken but would like to get some feedback in this if possible

thanks in advance

**Comment by Syberspace** [comment]
You are correct. The error message is sometimes wrongly displayed. Since it does not affect the workflow you can just ignore it. #18 attemts to fix the message. We'll merge this as soon as possible.
