### ISSUE TITLE
Update changes page's URL, not keeping the original.

### ISSUE THREAD

**Issue by wgshef** [tao-software/tao-schedule-update#19]
My posts are saved to a url in the format "archive/year/monthnum/posttitle".
When using Schedule Update, if it is a new month, then the monthnum on the page changes. For example, an existing post at "archive/2018/05/posttitle" is scheduled to update in June. When it updates, the url becomes "archive/2018/06/posttitle".

If I have other posts that are linked to this page, that breaks those links.
Is there a way to have the update NOT update the URL?

When I noticed this, I was doing recursive scheduled updates. Not sure if that is a factor or not.

**Comment by Syberspace** [comment]
You can use the Filter `TAO_ScheduleUpdate\publish_post_date` to set the date at the time of publishing. See https://github.com/tao-software/tao-schedule-update/blob/9b1909625fe7868a271c5c8160effc0110bf84b7/tao-schedule-update.php#L706-L713 for documentation

**Comment by wgshef** [comment]
How do I use this?
Where is the documentation that describes this?

**Comment by Syberspace** [comment]
The documentation is right there in the snippet i posted.
For further info on how to use that filter feel free to read the full source code.
