### ISSUE TITLE
Multiple Scheduled Revisions

### ISSUE THREAD

**Issue by timbuckingham** [tao-software/tao-schedule-update#24]
I've noticed that if you click "Scheduled Update" for a page more than once it actually creates multiple scheduled revisions rather than modifying the existing scheduled revision. I guess this could be intentional behavior / a feature but it seems confusing as a user. Unless you remember the URL that was generated for the first revision then you're unable to go back and edit it (unless I'm missing something). I think maybe showing a "Edit Existing Scheduled Update" and "Create New Scheduled Update" links would be a helpful UI change.

**Comment by Syberspace** [comment]
this is intended behaviour.
suppose you have a baseline page you want to create two different versions of in the future. for example a page with images themed around summer/swimwear. you could take this as a baseline for the autumn and winter collection, change a couple of images and texts but leave the general layout intact.

**Comment by timbuckingham** [comment]
I figured it was possibly intended behavior, but what about the way to easily edit the existing scheduled update without having to remember the URL?
