### ISSUE TITLE
Scheduled Revision Indexable

### ISSUE THREAD

**Issue by timbuckingham** [tao-software/tao-schedule-update#25]
The new URLs that are created by scheduled updates are presently indexable. If it's possible to have the plugin automatically pass "X-Robots-Tag: noindex" headers when WordPress is serving up a post with the post_status of "tao_sc_publish" I think that would be ideal.

**Comment by jnorell** [comment]
Maybe I misunderstand the issue here, but when I open the url to a scheduled post and I am not logged in, I just get a not found page (404 error).  It does display when I'm logged in, but that won't matter for bot indexing.

**Comment by timbuckingham** [comment]
That makes complete sense! Sorry I didn’t test when logged out. Closing!
