### ISSUE TITLE
How to see the scheduled date and time for scheduled post?

### ISSUE THREAD

**Issue by umarfarukm** [tao-software/tao-schedule-update#6]
Just wanted to know where can i see the scheduled date and time of post after the post was scheduled? As of now i am not able to find it.

By the way it really works good!

**Comment by Syberspace** [comment]
There should be a separate column that displays the date and time of each scheduled update. 
If that column isn't visible to you you might have to turn it on via the screen options in the top right (below your username)  
![tsu-releasedate](https://cloud.githubusercontent.com/assets/2759974/15214344/bbde9e84-184c-11e6-8756-3179707cf96e.png)

**Comment by umarfarukm** [comment]
YES! We actually see them under page,post (and other default post_type). 

We are using 'The Events Calendar' (post_type = tribe_events). How to enable to the custom post type pages?

**Comment by Syberspace** [comment]
I am not familiar with "The Events Calendar". But from what my short tests have shown I would assume they are using a custom built table layout that only mimics the wordpress builtin `WP_Table` but does not respect additional columns.

I will see if I can find a solution for this incompatibility.

**Comment by Syberspace** [comment]
My assumption was wrong. "The Events Calendar" uses the standard wordpress table functionalities.
The problem is that the tribe_events post type is registered after tao-schedule-update is done initializing.

**Comment by Syberspace** [comment]
i'll try to push the updated code with a new version number to the wordpress.org repo this week, can't promise anything though.
