### ISSUE TITLE
Possible to preview the updated content before the schedule?

### ISSUE THREAD

**Issue by umarfarukm** [tao-software/tao-schedule-update#9]
Under Scheduled update list in WP it seems that if you click on it you come to the original (live version) instead of scheduled update version. Wondering anyway to see the preview of updated content?

**Comment by umarfarukm** [comment]
If i need to alter the correction of a scheduled update, does it need to schedule a new update? not in the existing scheduled updated.

**Comment by Syberspace** [comment]
Try updating to version 1.11

It includes recursive scheduling and the possibility to set the visibility of scheduled updates.
